apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
# - apiVersion: v1
#   kind: Namespace
#   metadata:
#     name: vw-amq
# - apiVersion: operators.coreos.com/v1alpha1
#   kind: Subscription
#   metadata:
#     labels:
#       operators.coreos.com/amq-broker-rhel8.openshift-operators: ""
#     name: amq-broker-rhel8
#     namespace: openshift-operators
#   spec:
#     channel: 7.10.x
#     installPlanApproval: Automatic
#     name: amq-broker-rhel8
#     source: redhat-operators
#     sourceNamespace: openshift-marketplace
#     startingCSV: amq-broker-operator.v7.10.2-opr-2
# - apiVersion: operators.coreos.com/v1alpha1
#   kind: Subscription
#   metadata:
#     labels:
#       operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
#     name: openshift-pipelines-operator-rh
#     namespace: openshift-operators
#   spec:
#     channel: latest
#     installPlanApproval: Automatic
#     name: openshift-pipelines-operator-rh
#     source: redhat-operators
#     sourceNamespace: openshift-marketplace
#     startingCSV: openshift-pipelines-operator-rh.v1.9.0
- apiVersion: broker.amq.io/v1beta1
  kind: ActiveMQArtemis
  metadata:
    name: ex-aao
    namespace: vw-amq
  spec:
    acceptors:
      - name: core-acceptor
        port: 61616
        protocols: core
        sslEnabled: false
        expose: true
      - name: amqp-acceptor
        port: 5672
        protocols: amqp
        sslEnabled: false
        expose: true
      - name: mqtt-acceptor
        port: 1883
        protocols: mqtt
        sslEnabled: false
        expose: true
    console:
      expose: true
    deploymentPlan:
      storage:
        size: 100Gi
      image: placeholder
      jolokiaAgentEnabled: false
      journalType: nio
      managementRBACEnabled: true
      messageMigration: false
      requireLogin: false
      persistenceEnabled: true
      enableMetricsPlugin: true
      size: 2
      clustered: true
    adminUser: admin
    adminPassword: admin
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      application: ex-aao
      component: service-monitor
    name: vw-amq-broker
    namespace: vw-amq
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: wconsj-0
      scheme: http
    selector:
      matchLabels:
        ActiveMQArtemis: ex-aao
        application: ex-aao-app